### ISSUE TITLE
Error when binding net addr to 0.0.0.0

### ISSUE THREAD

**Issue by labkode** [owncloud/ocis-wopiserver#7]
When binding the server to `0.0.0.0` is gives the following error:

```
ocis-wopiserver server --http-addr 0.0.0.0:1111
{"level":"error","service":"wopiserver","error":"address ::1:1111: too many colons in address","transport":"http","time":"2021-06-21T11:10:23+02:00","message":"Failed to start server"}

```

When running with localhost it works:
```
ocis-wopiserver server --http-addr localhost:1111
```

**Comment by wkloucek** [comment]
Note: @labkode reported that oCIS can be started without problems

**Comment by wkloucek** [comment]
Could you please try `--http-addr '[0.0.0.0]:1111'` / `--http-addr '[::0]:1111'` ?

Edit: more about the square bracket notation: https://pkg.go.dev/net#Dial

**Comment by labkode** [comment]
@wkloucek same error:
```
[13:51][root@cbox-ocisdev-03 (ocis_dev:box/ocis) ~]# ocis-wopiserver server --http-addr "[0.0.0.0]:9505"
{"level":"info","service":"wopiserver","time":"2021-06-21T13:51:54+02:00","message":"Continue without config"}
{"level":"info","service":"wopiserver","time":"2021-06-21T13:51:54+02:00","message":"Continue without config"}
{"level":"info","service":"wopiserver","transport":"http","addr":"[0.0.0.0]:9505","time":"2021-06-21T13:51:54+02:00","message":"starting server"}
{"level":"info","service":"wopiserver","transport":"debug","addr":"0.0.0.0:9109","time":"2021-06-21T13:51:54+02:00","message":"starting server"}
2021-06-21 13:51:54  file=v3@v3.5.1-0.20210217182006-0f0ace1a44a9/service.go:192 level=info Starting [service] com.owncloud.web.
{"level":"info","service":"wopiserver","transport":"http","time":"2021-06-21T13:51:54+02:00","message":"Shutting down server"}
2021-06-21 13:51:54  file=v3@v3.0.0-20210408173139-0d57213d3f5c/http.go:255 level=info Listening on [::]:9505
2021-06-21 13:51:54  file=v3@v3.0.0-20210408173139-0d57213d3f5c/http.go:169 level=info Registering node: com.owncloud.web.-fb7ddaf2-3664-4b8a-9e34-e1134656aa6a
{"level":"error","service":"wopiserver","error":"address ::1:9505: too many colons in address","transport":"http","time":"2021-06-21T13:51:54+02:00","message":"Failed to start server"}



[13:51][root@cbox-ocisdev-03 (ocis_dev:box/ocis) ~]# ocis-wopiserver server --http-addr "[::0]:9505"
{"level":"info","service":"wopiserver","time":"2021-06-21T13:52:07+02:00","message":"Continue without config"}
{"level":"info","service":"wopiserver","time":"2021-06-21T13:52:07+02:00","message":"Continue without config"}
{"level":"info","service":"wopiserver","transport":"http","addr":"[::0]:9505","time":"2021-06-21T13:52:07+02:00","message":"starting server"}
{"level":"info","service":"wopiserver","transport":"debug","addr":"0.0.0.0:9109","time":"2021-06-21T13:52:07+02:00","message":"starting server"}
2021-06-21 13:52:07  file=v3@v3.5.1-0.20210217182006-0f0ace1a44a9/service.go:192 level=info Starting [service] com.owncloud.web.
{"level":"info","service":"wopiserver","transport":"http","time":"2021-06-21T13:52:07+02:00","message":"Shutting down server"}
2021-06-21 13:52:07  file=v3@v3.0.0-20210408173139-0d57213d3f5c/http.go:255 level=info Listening on [::]:9505
2021-06-21 13:52:07  file=v3@v3.0.0-20210408173139-0d57213d3f5c/http.go:169 level=info Registering node: com.owncloud.web.-f8a2ce75-221e-4dff-b97d-6307d8b74999
{"level":"error","service":"wopiserver","error":"address ::1:9505: too many colons in address","transport":"http","time":"2021-06-21T13:52:07+02:00","message":"Failed to start server"}
```

**Comment by labkode** [comment]
If I use `[::1]:9505` looks like it works:

```
[13:53][root@cbox-ocisdev-03 (ocis_dev:box/ocis) ~]# ocis-wopiserver server --http-addr "[::1]:9505"
{"level":"info","service":"wopiserver","time":"2021-06-21T13:53:29+02:00","message":"Continue without config"}
{"level":"info","service":"wopiserver","time":"2021-06-21T13:53:29+02:00","message":"Continue without config"}
{"level":"info","service":"wopiserver","transport":"http","addr":"[::1]:9505","time":"2021-06-21T13:53:29+02:00","message":"starting server"}
{"level":"info","service":"wopiserver","transport":"debug","addr":"0.0.0.0:9109","time":"2021-06-21T13:53:29+02:00","message":"starting server"}
2021-06-21 13:53:29  file=v3@v3.5.1-0.20210217182006-0f0ace1a44a9/service.go:192 level=info Starting [service] com.owncloud.web.
2021-06-21 13:53:29  file=v3@v3.0.0-20210408173139-0d57213d3f5c/http.go:255 level=info Listening on [::1]:9505
{"level":"info","service":"wopiserver","transport":"http","time":"2021-06-21T13:53:29+02:00","message":"Shutting down server"}
2021-06-21 13:53:29  file=v3@v3.0.0-20210408173139-0d57213d3f5c/http.go:169 level=info Registering node: com.owncloud.web.-f730bbd9-e80e-475a-9d8d-885639a7ff4a
2021-06-21 13:53:29  file=v3@v3.0.0-20210408173139-0d57213d3f5c/http.go:209 level=info Deregistering node: com.owncloud.web.-f730bbd9-e80e-475a-9d8d-885639a7ff4a
```

**Comment by wkloucek** [comment]
@refs Do you have an idea? I'm pretty clueless

**Comment by refs** [comment]
I have not dug into why it does work with the brackets, but have ran into this error when ipv6 is enabled in my machine. Reading up in your link to the docs I see why it works with brackets:

>  If the host is a literal IPv6 address it must be enclosed in square brackets, as in "[2001:db8::1]:80" or "[fe80::1%zone]:80".

I pretty much think the logic is assuming too much and treats ipv4 as ipv6 (as in: `tcp.Dial("::1:9505")` -> this is invalid). A simple guard should suffice and provide support out of the box to both ipv4 and ipv6.

**Comment by refs** [comment]
I'm confused as to how `0.0.0.0` gets translated into `::1`. We're basically handing over the address to go-micro: https://github.com/owncloud/ocis/blob/dc932c690487118ed7c0cbd0911856975289da72/proxy/pkg/server/http/server.go#L50 without any transformation.

**Comment by wkloucek** [comment]
`0.0.0.0` and `[::0]` have the same meaning: bind to all available interfaces.

These also include `127.0.0.1` and `[::1]` (localhost). This is the theory. But in reality our binary (somewhere deep down in the chain) uses `::1` only as IPV6 localhost, but I couldn't find the point where it will be translated.

**Comment by refs** [comment]
I believe it is in go-micro. I'll do some digging and keep us in the loop 👍

**Comment by refs** [comment]
@wkloucek the corresponding go-micro line that logs is:

`2021-06-23 12:50:14  file=v3@v3.0.0-20210408173139-0d57213d3f5c/http.go:255 level=info Listening on [::]:1111`

digging into go-micro for the version `0d57213d3f5c`: https://github.com/asim/go-micro/blob/4c1f81dadb47b90f71f37c4f845af5821ef80a47/plugins/server/http/http.go#L255

that listener contains the following information (when ipv6 is enabled):

![image](https://user-images.githubusercontent.com/6905948/123085101-2df5eb80-d422-11eb-911b-62e0cdff53d9.png)

that gets parsed as:

![image](https://user-images.githubusercontent.com/6905948/123085193-436b1580-d422-11eb-9ebe-a940fc81615b.png)

Digging into the lowest level we find this syscall:

```go
if supportsIPv4map() && family == syscall.AF_INET6 && sotype != syscall.SOCK_RAW {
// Allow both IP versions even if the OS default
// is otherwise. Note that some operating systems
// never admit this option.
syscall.SetsockoptInt(s, syscall.IPPROTO_IPV6, syscall.IPV6_V6ONLY, boolint(ipv6only))
}
```

where the condition evaluates to true, sets the socket options to IPv6. By this time the fd does not have any address set, this is acquired here:

```go
...
fd.setAddr(fd.addrFunc()(lsa), nil)
...
```

in [`sock_posix.go` from the stdlib](https://golang.org/src/net/sock_posix.go#L203).

and ultimately sets the address to an ipv6 address:

```go
func sockaddrToTCP(sa syscall.Sockaddr) Addr {
	switch sa := sa.(type) {
	case *syscall.SockaddrInet4:
		return &TCPAddr{IP: sa.Addr[0:], Port: sa.Port}
	case *syscall.SockaddrInet6:
		return &TCPAddr{IP: sa.Addr[0:], Port: sa.Port, Zone: zoneCache.name(int(sa.ZoneId))}
	}
	return nil
}
```

At least in my system.

Now, debugging session apart, with ipv6 enabled in my system, I cannot reproduce @labkode's issue:

![image](https://user-images.githubusercontent.com/6905948/123088622-423be780-d426-11eb-9788-c6e7c4744aca.png)

And sub-sequentially running:

`bin/wopiserver server --http-addr "[::1]:1111"`
`bin/wopiserver server --http-addr "[0.0.0.0]:1111"`
`bin/wopiserver server --http-addr "[::0]:1111"`

work for me.

**Comment by refs** [comment]
I'm running on `go version go1.16.2 darwin/amd64`

**Comment by refs** [comment]
I'm, however, able to reproduce something similar under this circumstances:

1. disable ipv6 in my system
2. run `bin/wopiserver server --http-addr ::1:1111`

that throws

```json
{
   "level":"error",
   "service":"wopiserver",
   "error":"listen tcp: address ::1:1111: too many colons in address",
   "transport":"http",
   "time":"2021-06-23T13:41:28+02:00",
   "message":"Failed to start server"
}
```

**Comment by wkloucek** [comment]
this project is depreciated and will be archived

the same error is tracked in oCIS: https://github.com/owncloud/ocis/issues/2300
